(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* Utility function *)
\[ScriptU][\[ScriptC]t_]:= \[ScriptC]t^(1-\[Rho])/(1-\[Rho]);
\[ScriptU]P[\[ScriptC]t_]:= \[ScriptC]t^-\[Rho];
\[ScriptU]PP[\[ScriptC]t_]:= -\[Rho] \[ScriptC]t^(-\[Rho]-1);


(* Production technology *)
\[CapitalDigamma][\[ScriptK]t_]:=\[Dalet] \[ScriptK]t+\[ScriptK]t^\[Alpha];
\[CapitalDigamma]P[\[ScriptK]t_]:=\[Dalet] +\[Alpha] \[ScriptK]t^(\[Alpha]-1); 
\[CapitalDigamma]PP[\[ScriptK]t_]:=\[Alpha] (\[Alpha]-1)\[ScriptK]t^(\[Alpha]-2);     


(* Adjustment cost function *)
\[ScriptJ][\[ScriptI]t_,\[ScriptK]t_]:=((\[Omega] \[ScriptK]t)/2) (\[ScriptI]t/\[ScriptK]t-\[Delta])^2;
\[ScriptJ]\[ScriptI][\[ScriptI]t_,\[ScriptK]t_]:=\[Omega] (\[ScriptI]t/\[ScriptK]t-\[Delta]);
\[ScriptJ]\[ScriptI]\[ScriptI][\[ScriptI]t_,\[ScriptK]t_]:=\[Omega]/\[ScriptK]t;
\[ScriptJ]\[ScriptI]\[ScriptK][\[ScriptI]t_,\[ScriptK]t_]:= (-\[Omega] \[ScriptI]t)/\[ScriptK]t^2;
\[ScriptJ]\[ScriptK][\[ScriptI]t_,\[ScriptK]t_]:=\[ScriptJ][\[ScriptI]t,\[ScriptK]t]/\[ScriptK]t-(\[ScriptI]t/\[ScriptK]t) \[ScriptJ]\[ScriptI][\[ScriptI]t,\[ScriptK]t];
\[ScriptJ]\[ScriptK]\[ScriptI][\[ScriptI]t_,\[ScriptK]t_]:=\[ScriptJ]\[ScriptI][\[ScriptI]t,\[ScriptK]t]/\[ScriptK]t-1/\[ScriptK]t \[ScriptJ]\[ScriptI][\[ScriptI]t,\[ScriptK]t]-(\[ScriptI]t/\[ScriptK]t) \[ScriptJ]\[ScriptI]\[ScriptI][\[ScriptI]t,\[ScriptK]t];
\[ScriptJ]\[ScriptK]\[ScriptK][\[ScriptI]t_,\[ScriptK]t_]:=-\[ScriptJ][\[ScriptI]t,\[ScriptK]t]/\[ScriptK]t^2+\[ScriptJ]\[ScriptK][\[ScriptI]t,\[ScriptK]t]/\[ScriptK]t+\[ScriptI]t/\[ScriptK]t^2 \[ScriptJ]\[ScriptI][\[ScriptI]t,\[ScriptK]t]-\[ScriptI]t/\[ScriptK]t \[ScriptJ]\[ScriptI]\[ScriptK][\[ScriptI]t,\[ScriptK]t];


\[Lambda]Func[\[ScriptK]t_]:=\[ScriptU]P[\[ScriptC]Func[\[ScriptK]t]] (\[Dalet] \[ScriptJ]\[ScriptI][\[ScriptI]Func[\[ScriptK]t],\[ScriptK]t]-\[ScriptJ]\[ScriptK][\[ScriptI]Func[\[ScriptK]t],\[ScriptK]t]+\[CapitalDigamma]P[\[ScriptK]t]);
\[DoubleStruckCapitalR]Func[\[ScriptK]t_]:=Block[{\[ScriptK]tp1},
\[ScriptK]tp1=\[Dalet] \[ScriptK]t+\[ScriptI]Func[\[ScriptK]t];
(\[Dalet] \[ScriptJ]\[ScriptI][\[ScriptI]Func[\[ScriptK]tp1],\[ScriptK]tp1]-\[ScriptJ]\[ScriptK][\[ScriptI]Func[\[ScriptK]tp1],\[ScriptK]tp1]+\[CapitalDigamma]P[\[ScriptK]tp1])/(\[ScriptJ]\[ScriptI][\[ScriptI]Func[\[ScriptK]t],\[ScriptK]t]+1)
];


\[ScriptK]SS:=(((1/\[Beta])-\[Dalet])/\[Alpha])^(1/(\[Alpha]-1)); 
\[ScriptI]SS:=\[ScriptK]SS \[Delta];
\[ScriptJ]SS:=\[ScriptJ][\[ScriptI]SS,\[ScriptK]SS];
\[ScriptC]SS:=\[ScriptK]SS^\[Alpha]-\[ScriptI]SS-\[ScriptJ]SS;


BackShoot[InitialPoints_]:=Block[{},
BackShootList={};
\[ScriptK]tp1=InitialPoints[[1]];
\[ScriptI]tp1=InitialPoints[[2]];
\[ScriptJ]tp1=\[ScriptJ][\[ScriptI]tp1,\[ScriptK]tp1];
\[ScriptC]tp1=\[ScriptK]tp1^\[Alpha]-\[ScriptI]tp1-\[ScriptJ]tp1;
If[\[ScriptK]tp1<\[ScriptK]SS,
\[ScriptK]tp1GuessF:=\[ScriptK]tp1-10^-10;\[ScriptK]tp1MinF:=X+10^-10/.FindRoot[X^\[Alpha]-(\[ScriptK]tp1-(1-\[Delta])X)-\[ScriptJ][\[ScriptK]tp1-(1-\[Delta])X,X]==0,{X,\[ScriptK]tp1-10^-10,10^-10,\[ScriptK]tp1}];\[ScriptK]tp1MaxF:=\[ScriptK]tp1,
\[ScriptK]tp1GuessF:=\[ScriptK]tp1+10^-10;\[ScriptK]tp1MinF:=\[ScriptK]tp1;\[ScriptK]tp1MaxF:=4 \[ScriptK]SS];
While[
Chop[\[ScriptK]tp1]>10^-5 && \[ScriptK]tp1<3 \[ScriptK]SS,
BackShootList=Prepend[BackShootList,{\[ScriptK]tp1,\[ScriptI]tp1,\[ScriptC]tp1,\[ScriptJ]tp1}];
{\[ScriptK]tp1Guess,\[ScriptK]tp1Min,\[ScriptK]tp1Max}={\[ScriptK]tp1GuessF,\[ScriptK]tp1MinF,\[ScriptK]tp1MaxF};
\[ScriptK]t=X/.FindRoot[(1+\[ScriptJ]\[ScriptI][\[ScriptK]tp1-(1-\[Delta])X,X])\[ScriptU]P[X^\[Alpha]-(\[ScriptK]tp1-(1-\[Delta])X)-\[ScriptJ][\[ScriptK]tp1-(1-\[Delta])X,X]]==\[Beta] \[ScriptU]P[\[ScriptK]tp1^\[Alpha]-\[ScriptI]tp1-\[ScriptJ][\[ScriptI]tp1,\[ScriptK]tp1]](\[CapitalDigamma]P[\[ScriptK]tp1]+(1-\[Delta])\[ScriptJ]\[ScriptI][\[ScriptI]tp1,\[ScriptK]tp1]-\[ScriptJ]\[ScriptK][\[ScriptI]tp1,\[ScriptK]tp1]),{X,\[ScriptK]tp1Guess,\[ScriptK]tp1Min,\[ScriptK]tp1Max}];
\[ScriptI]t=\[ScriptK]tp1-(1-\[Delta])\[ScriptK]t;
\[ScriptJ]t=\[ScriptJ][\[ScriptI]t,\[ScriptK]t];
\[ScriptC]t=\[ScriptK]t^\[Alpha]-\[ScriptI]t-\[ScriptJ]t;
{\[ScriptK]tp1,\[ScriptI]tp1,\[ScriptC]tp1,\[ScriptJ]tp1}={\[ScriptK]t,\[ScriptI]t,\[ScriptC]t,\[ScriptJ]t};
];
Return[BackShootList]];


(* This routine solves for the policy functions *)
SolvePolFunc:=Block[{},
(* Derivative of end of period capital with respect to beginning of period capital at the steady state *)
\[ScriptI]\[ScriptK]SS=X/.Solve[
(\[ScriptJ]\[ScriptI]\[ScriptI][\[ScriptI]SS,\[ScriptK]SS]X+\[ScriptJ]\[ScriptI]\[ScriptK][\[ScriptI]SS,\[ScriptK]SS])\[ScriptU]P[\[ScriptC]SS]+(\[ScriptJ]\[ScriptI][\[ScriptI]SS,\[ScriptK]SS]+1) \[ScriptU]PP[\[ScriptC]SS](\[Alpha] \[ScriptK]SS^(\[Alpha]-1)-X-\[ScriptJ]\[ScriptI][\[ScriptI]SS,\[ScriptK]SS]X-\[ScriptJ]\[ScriptK][\[ScriptI]SS,\[ScriptK]SS])==\[Beta]((\[CapitalDigamma]PP[\[ScriptK]SS](X+\[Dalet])+\[Dalet] \[ScriptJ]\[ScriptI]\[ScriptI][\[ScriptI]SS,\[ScriptK]SS]X+\[Dalet] \[ScriptJ]\[ScriptI]\[ScriptK][\[ScriptI]SS,\[ScriptK]SS](X+\[Dalet])-\[ScriptJ]\[ScriptK]\[ScriptI][\[ScriptI]SS,\[ScriptK]SS]X-\[ScriptJ]\[ScriptK]\[ScriptK][\[ScriptI]SS,\[ScriptK]SS](X+\[Dalet]))\[ScriptU]P[\[ScriptC]SS]+(\[CapitalDigamma]P[\[ScriptK]SS]+\[Dalet] \[ScriptJ]\[ScriptI][\[ScriptI]SS,\[ScriptK]SS]-\[ScriptJ]\[ScriptK][\[ScriptI]SS,\[ScriptK]SS])\[ScriptU]PP[\[ScriptC]SS](\[Alpha] \[ScriptK]SS^(\[Alpha]-1) (X+\[Dalet])-X-\[ScriptJ]\[ScriptI][\[ScriptI]SS,\[ScriptK]SS]X-\[ScriptJ]\[ScriptK][\[ScriptI]SS,\[ScriptK]SS](X+\[Dalet]))),X][[1]];

BackShootList1=BackShoot[{\[ScriptK]SS-\[CurlyEpsilon],\[ScriptI]SS+\[ScriptI]\[ScriptK]SS (-\[CurlyEpsilon])}];
BackShootListAugmented=BackShootList;
PrecisionAugmentationFactor = 3;(* Repeating BackShoot with different "wisely chosen" \[CurlyEpsilon] in order to improve quality of interpolation *)
Do[BackShootListAugmented = Join[BackShootListAugmented,BackShoot[BackShootList1[[-2,1;;2]]+(BackShootList1[[-1,1;;2]]-BackShootList1[[-2,1;;2]])(i/PrecisionAugmentationFactor)]],{i,PrecisionAugmentationFactor-1}];
StableArmBelowSS =Sort[BackShootListAugmented];

BackShootList1=BackShoot[{\[ScriptK]SS+\[CurlyEpsilon],\[ScriptI]SS+\[ScriptI]\[ScriptK]SS \[CurlyEpsilon]}];
BackShootListAugmented=BackShootList;
PrecisionAugmentationFactor = 3;(* Repeating BackShoot with different "wisely chosen" \[CurlyEpsilon] in order to improve quality of interpolation *)
Do[BackShootListAugmented = Join[BackShootListAugmented,BackShoot[BackShootList1[[-1,1;;2]]+(BackShootList1[[-2,1;;2]]-BackShootList1[[-1,1;;2]])(i/PrecisionAugmentationFactor)]],{i,PrecisionAugmentationFactor-1}];
StableArmAboveSS =Sort[BackShootListAugmented];

StableArmPoints= Sort[Union[Join[StableArmBelowSS,{{\[ScriptK]SS,\[ScriptI]SS,\[ScriptC]SS,\[ScriptJ]SS}},StableArmAboveSS]]];

\[ScriptI]Func=Interpolation[Transpose[{StableArmPoints[[All,1]],StableArmPoints[[All,2]]}],InterpolationOrder->1];
\[ScriptC]Func=Interpolation[Transpose[{StableArmPoints[[All,1]],StableArmPoints[[All,3]]}],InterpolationOrder->1];
\[ScriptJ]Func=Interpolation[Transpose[{StableArmPoints[[All,1]],StableArmPoints[[All,4]]}],InterpolationOrder->1];
];


InitializeSimData:=Block[{},\[ScriptK]tList={\[ScriptK]SS};\[Lambda]tList=\[ScriptC]tList=\[ScriptI]tList=\[DoubleStruckCapitalR]tp1List=\[ScriptJ]tList={}];


AddOnePeriod:=Block[{},
\[ScriptK]t=Last[\[ScriptK]tList];
AppendTo[\[Lambda]tList,\[Lambda]Func[\[ScriptK]t]];
AppendTo[\[ScriptC]tList,\[ScriptC]Func[\[ScriptK]t]];
AppendTo[\[ScriptI]tList,\[ScriptI]Func[\[ScriptK]t]];
AppendTo[\[DoubleStruckCapitalR]tp1List,\[DoubleStruckCapitalR]Func[\[ScriptK]t]];
AppendTo[\[ScriptJ]tList,\[ScriptJ]Func[\[ScriptK]t]];
AppendTo[\[ScriptK]tList,\[Dalet] \[ScriptK]t+Last[\[ScriptI]tList]];
];
