(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



\[CurlyEpsilon]=\[CurlyEpsilon]Base=10^-9; 
\[Rho]=\[Rho]Base=1.;    (* CRRA; \[Rho]=1.0 is log utility *)
\[Delta]=\[Delta]Base=0.06;   (* depreciation rate *)
\[Alpha]=\[Alpha]Base=0.36;  (* capital-labor ratio *)
(* Picking a huge value for the adj cost parameter so difference w Ramsey will be obvious *)
(* A more common calibration is 0.10 *)
\[Omega]=\[Omega]Base=10.0;   (* adjustment cost parameter *)
\[Beta]=\[Beta]Base=0.96; (* intertemporal discount factor *)
\[Dalet]:=1-\[Delta];  (* depreciation factor *)


PreShockPeriods=5;
AfterShockPeriods=35;
