(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



ClearAll["Global`*"];
Needs["PlotLegends`"];
If[Length[$FrontEnd] > 0, NBDir = SetDirectory[NotebookDirectory[]]];(* If running from the Notebook interface *)
If[Length[$FrontEnd] == 0,SetDirectory["/Volumes/Data/Courses/Choice/LectureNotes/Growth/Handouts/qRamsey/Code/Mathematica/"]];

SetDirectory[NotebookDirectory[]];
SetOptions[Plot
,BaseStyle->{FontSize->16},PlotRange->All,Ticks->None,PlotStyle->{Thick}];
SetOptions[ListPlot
,BaseStyle->{FontSize->16},PlotRange->All,Ticks->None,PlotStyle->{Black,PointSize[Medium]}];
<<qRamseyFunctions.m;
{\[ScriptC]Color,\[ScriptI]Color,\[ScriptJ]Color}={Darker[Green],\[ScriptI]Color=Red,\[ScriptJ]Color=Black};
CostAdj0Thickness=Thickness[Medium];
CostAdjAltThickness=Thickness[Large];


<<qRamseyParamsBase.m;
\[Omega]=0; (* \[Omega] measures size of cost of adjustment *)
Quiet[SolvePolFunc];(* Quiet[] supresses some error messages caused by \[Omega]=0 that do not actually signal a failed solution *)
{\[ScriptC]FuncAdjCost0,\[ScriptI]FuncAdjCost0,\[ScriptJ]FuncAdjCost0}={\[ScriptC]Func,\[ScriptI]Func,\[ScriptJ]Func};


<<qRamseyParamsBase.m;
SolvePolFunc;
{\[ScriptC]FuncBase,\[ScriptI]FuncBase,\[ScriptJ]FuncBase}={\[ScriptC]Func,\[ScriptI]Func,\[ScriptJ]Func};


<<qRamseyParamsBase.m;
\[Omega]=5*\[Omega]Base;
SolvePolFunc;
{\[ScriptC]FuncAdjCostHi,\[ScriptI]FuncAdjCostHi,\[ScriptJ]FuncAdjCostHi}={\[ScriptC]Func,\[ScriptI]Func,\[ScriptJ]Func};


PolFuncAdjCost0VsHi=Show[Plot[{\[ScriptC]FuncAdjCost0[\[ScriptK]],\[ScriptI]FuncAdjCost0[\[ScriptK]],\[ScriptJ]FuncAdjCost0[\[ScriptK]],\[ScriptC]FuncAdjCostHi[\[ScriptK]],\[ScriptI]FuncAdjCostHi[\[ScriptK]],\[ScriptJ]FuncAdjCostHi[\[ScriptK]]},{\[ScriptK],0,2\[ScriptK]SS}
,PlotStyle->{{CostAdj0Thickness,\[ScriptC]Color},{CostAdj0Thickness,\[ScriptI]Color},{CostAdj0Thickness,\[ScriptJ]Color}
,{CostAdjAltThickness,Dashed,\[ScriptC]Color},{CostAdjAltThickness,Dashed,\[ScriptI]Color},{CostAdjAltThickness,Dashed,\[ScriptJ]Color}}
,AxesLabel->{"\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\)"} ,Ticks->{{{\[ScriptK]SS,"\!\(\*OverscriptBox[\(\[ScriptK]\), \(\[Hacek]\)]\)"}},{}}],
Graphics[{
Text["\!\(\*SubscriptBox[\(\[ScriptC]\), \(t\)]\)",{\[ScriptK]SS,\[ScriptC]SS +.2}],
Text["\!\(\*SubscriptBox[\(\[ScriptI]\), \(t\)]\)",{\[ScriptK]SS,\[ScriptI]SS +.2}],
Text["\[LowerLeftArrow] \!\(\*SubscriptBox[\(\[ScriptJ]\), \(t\)]\)",{\[ScriptK]SS/2,\[ScriptI]SS /3}]
}]
];

Print["Solid=No costs (standard Ramsey); Dashing=With high adj costs (q-Ramsey)"];Print[PolFuncAdjCost0VsHi];


Export["../../Figures/PolFuncAdjCost0VsHi.pdf",PolFuncAdjCost0VsHi];
Export["../../Figures/PolFuncAdjCost0VsHi.eps",PolFuncAdjCost0VsHi];
Export["../../Figures/PolFuncAdjCost0VsHi.png",PolFuncAdjCost0VsHi,ImageSize->{72 8.,72 8./GoldenRatio}];


PolFuncAdjCost0VsBase=Show[Plot[{\[ScriptC]FuncAdjCost0[\[ScriptK]],\[ScriptI]FuncAdjCost0[\[ScriptK]],\[ScriptJ]FuncAdjCost0[\[ScriptK]],\[ScriptC]FuncBase[\[ScriptK]],\[ScriptI]FuncBase[\[ScriptK]],\[ScriptJ]FuncBase[\[ScriptK]]},{\[ScriptK],0,2\[ScriptK]SS}
,PlotStyle->{{CostAdj0Thickness,\[ScriptC]Color},{CostAdj0Thickness,\[ScriptI]Color},{CostAdj0Thickness,\[ScriptJ]Color}
,{CostAdjAltThickness,Dashed,\[ScriptC]Color},{CostAdjAltThickness,Dashed,\[ScriptI]Color},{CostAdjAltThickness,Dashed,\[ScriptJ]Color}}
,AxesLabel->{"\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\)"} ,Ticks->{{{\[ScriptK]SS,"\!\(\*OverscriptBox[\(\[ScriptK]\), \(\[Hacek]\)]\)"}},{}}],
Graphics[{
Text["\!\(\*SubscriptBox[\(\[ScriptC]\), \(t\)]\)",{\[ScriptK]SS,\[ScriptC]SS +.2}],
Text["\!\(\*SubscriptBox[\(\[ScriptI]\), \(t\)]\)",{\[ScriptK]SS,\[ScriptI]SS +.2}],
Text["\[LowerLeftArrow] \!\(\*SubscriptBox[\(\[ScriptJ]\), \(t\)]\)",{\[ScriptK]SS/2,\[ScriptI]SS /3}]
}]];
Print["Solid=Ramsey;Dashed=With baseline Adj Costs (q-Ramsey)"];Print[PolFuncAdjCost0VsBase];


Export["../../Figures/PolFuncAdjCost0VsBase.pdf",PolFuncAdjCost0VsBase];
Export["../../Figures/PolFuncAdjCost0VsBase.eps",PolFuncAdjCost0VsBase];
Export["../../Figures/PolFuncAdjCost0VsBase.png",PolFuncAdjCost0VsBase,ImageSize->{72 8.,72 8./GoldenRatio}];


<<qRamseyParamsBase.m;
\[Rho]=3.;
\[Omega]=0;
Quiet[SolvePolFunc];
{\[ScriptC]FuncCostAdj0AndRRAHi,\[ScriptI]FuncCostAdj0AndRRAHi,\[ScriptJ]FuncCostAdj0AndRRAHi}={\[ScriptC]Func,\[ScriptI]Func,\[ScriptJ]Func};


PolFuncRRALoVsHi=Show[
Plot[{\[ScriptC]FuncAdjCost0[\[ScriptK]],\[ScriptI]FuncAdjCost0[\[ScriptK]],\[ScriptJ]FuncAdjCost0[\[ScriptK]],\[ScriptC]FuncCostAdj0AndRRAHi[\[ScriptK]],\[ScriptI]FuncCostAdj0AndRRAHi[\[ScriptK]],\[ScriptJ]FuncCostAdj0AndRRAHi[\[ScriptK]]},{\[ScriptK],0,2\[ScriptK]SS},PlotStyle->{{CostAdj0Thickness,\[ScriptC]Color},{CostAdj0Thickness,\[ScriptI]Color},{CostAdj0Thickness,\[ScriptJ]Color},{Thick,Dashed,\[ScriptC]Color},{Thick,Dashed,\[ScriptI]Color},{Thick,Dashed,\[ScriptJ]Color}},AxesLabel->{"\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\)"} ,Ticks->{{{\[ScriptK]SS,"\!\(\*OverscriptBox[\(\[ScriptK]\), \(\[Hacek]\)]\)"}},{}}],
Graphics[{
Text["\!\(\*SubscriptBox[\(\[ScriptC]\), \(t\)]\)",{\[ScriptK]SS,\[ScriptC]SS +.2}],
Text["\!\(\*SubscriptBox[\(\[ScriptI]\), \(t\)]\)",{\[ScriptK]SS,\[ScriptI]SS +.2}]}]];
Print[PolFuncRRALoVsHi];


Export["../../Figures/PolFuncRRALoVsHi.pdf",PolFuncRRALoVsHi];
Export["../../Figures/PolFuncRRALoVsHi.eps",PolFuncRRALoVsHi];
Export["../../Figures/PolFuncRRALoVsHi.png",PolFuncRRALoVsHi,ImageSize->{72 8.,72 8./GoldenRatio}];


<<qRamseyParamsBase.m;
\[Omega]=0;
Quiet[SolvePolFunc];
InitializeSimData;
Do[AddOnePeriod,{PreShockPeriods}];
\[Beta]=0.98;
\[Omega]=0;
Quiet[SolvePolFunc];
Do[AddOnePeriod,{AfterShockPeriods}];


PatRiseAdjCost0=GraphicsGrid[{
{\[ScriptK]TimeAdjCost0=ListPlot[\[ScriptK]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptK]tList].95}],
\[Lambda]TimeAdjCost0=ListPlot[\[Lambda]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[Lambda]\), \(t\)]\)"},AxesOrigin->{0,Min[\[Lambda]tList].95}]},
{\[ScriptI]TimeAdjCost0=ListPlot[\[ScriptI]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptI]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptI]tList].9}],
\[ScriptC]TimeAdjCost0=ListPlot[\[ScriptC]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptC]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptC]tList].95}]},{\[DoubleStruckCapitalR]TimeAdjCost0=ListPlot[\[DoubleStruckCapitalR]tp1List,AxesLabel->{"t","\!\(\*SubscriptBox[\(R\), \(t + 1\)]\)"},AxesOrigin->{0,Min[\[DoubleStruckCapitalR]tp1List].99}],\[ScriptJ]TimeAdjCost0=ListPlot[\[ScriptJ]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptJ]\), \(t\)]\)"},AxesOrigin->{0,0}]
}},ImageSize->600];
(*
Print[PatRiseAdjCost0];
Export["../../Figures/PatRiseAdjCost0.pdf",PatRiseAdjCost0];
Export["../../Figures/PatRiseAdjCost0.eps",PatRiseAdjCost0];
Export["../../Figures/PatRiseAdjCost0.png",PatRiseAdjCost0,ImageSize->{72 8.,72 8./GoldenRatio}];
*)



<<qRamseyParamsBase.m;
Quiet[SolvePolFunc];
InitializeSimData;
Do[AddOnePeriod,{PreShockPeriods}];
\[Beta]=0.98;
Quiet[SolvePolFunc];
Do[AddOnePeriod,{AfterShockPeriods}];


SetOptions[ListPlot,PlotStyle->{Red,PointSize[Medium]}];
PatRiseAdjCostBase=GraphicsGrid[{
{\[ScriptK]TimeAdjCostBase=ListPlot[\[ScriptK]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptK]tList].95}],
\[Lambda]TimeAdjCostBase=ListPlot[\[Lambda]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[Lambda]\), \(t\)]\)"},AxesOrigin->{0,Min[\[Lambda]tList].95}]},
{\[ScriptI]TimeAdjCostBase=ListPlot[\[ScriptI]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptI]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptI]tList].9}],
\[ScriptC]TimeAdjCostBase=ListPlot[\[ScriptC]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptC]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptC]tList].95}]},{\[DoubleStruckCapitalR]TimeAdjCostBase=ListPlot[\[DoubleStruckCapitalR]tp1List,AxesLabel->{"t","\!\(\*SubscriptBox[\(R\), \(t + 1\)]\)"},AxesOrigin->{0,Min[\[DoubleStruckCapitalR]tp1List].99}],\[ScriptJ]TimeAdjCostBase=ListPlot[\[ScriptJ]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptJ]\), \(t\)]\)"},AxesOrigin->{0,0}]
}},ImageSize->600];
SetOptions[ListPlot,PlotStyle->{Black,PointSize[Medium]}];
(*Print[PatRiseAdjCostBase];
Export["../../Figures/PatRiseAdjCostBase.pdf",PatRiseAdjCostBase];
Export["../../Figures/PatRiseAdjCostBase.eps",PatRiseAdjCostBase];
Export["../../Figures/PatRiseAdjCostBase.png",PatRiseAdjCostBase,ImageSize->{72 8.,72 8./GoldenRatio}];*)




PatRiseCostAdj0VsBase=GraphicsGrid[{
{Show[\[ScriptK]TimeAdjCostBase,\[ScriptK]TimeAdjCost0],Show[\[Lambda]TimeAdjCostBase,\[Lambda]TimeAdjCost0]}
,{Show[\[ScriptI]TimeAdjCostBase,\[ScriptI]TimeAdjCost0],Show[\[ScriptC]TimeAdjCostBase,\[ScriptC]TimeAdjCost0]}
,{Show[\[DoubleStruckCapitalR]TimeAdjCostBase,\[DoubleStruckCapitalR]TimeAdjCost0],Show[\[ScriptJ]TimeAdjCostBase,\[ScriptJ]TimeAdjCost0]}
},ImageSize->600,PlotRange->All];
Print[PatRiseCostAdj0VsBase];
Export["../../Figures/PatRiseCostAdj0VsBase.pdf",PatRiseCostAdj0VsBase];
Export["../../Figures/PatRiseCostAdj0VsBase.eps",PatRiseCostAdj0VsBase];
Export["../../Figures/PatRiseCostAdj0VsBase.png",PatRiseCostAdj0VsBase,ImageSize->{72 8.,72 8./GoldenRatio}];





<<qRamseyParamsBase.m;
\[Omega]=0; (* Basic Ramsey model first *)
Quiet[SolvePolFunc];
InitializeSimData;
Do[AddOnePeriod,{PreShockPeriods}];
\[ScriptK]tList[[-1]]=Last[\[ScriptK]tList]0.50; (* 50% of the capital is lost*)
Do[AddOnePeriod,{AfterShockPeriods}];


kDropCostAdj0=GraphicsGrid[{
{\[ScriptK]TimeCostAdj0=ListPlot[\[ScriptK]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptK]tList].95}],
\[Lambda]TimeCostAdj0=ListPlot[\[Lambda]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[Lambda]\), \(t\)]\)"},AxesOrigin->{0,Min[\[Lambda]tList].95}]},{\[ScriptI]TimeCostAdj0=ListPlot[\[ScriptI]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptI]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptI]tList].9}],\[ScriptC]TimeCostAdj0=ListPlot[\[ScriptC]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptC]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptC]tList].95}]},{
\[DoubleStruckCapitalR]TimeCostAdj0=ListPlot[\[DoubleStruckCapitalR]tp1List,AxesLabel->{"t","\!\(\*SubscriptBox[\(R\), \(t + 1\)]\)"},AxesOrigin->{0,Min[\[DoubleStruckCapitalR]tp1List].99}],\[ScriptJ]TimeCostAdj0=ListPlot[\[ScriptJ]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptJ]\), \(t\)]\)"},AxesOrigin->{0,0}]
}},ImageSize->600];
(*Print[kDropCostAdj0];
Export["../../Figures/kDropCostAdj0.pdf",kDropCostAdj0];
Export["../../Figures/kDropCostAdj0.eps",kDropCostAdj0];
Export["../../Figures/kDropCostAdj0.png",kDropCostAdj0,ImageSize->{72 8.,72 8./GoldenRatio}];
*)


<<qRamseyParamsBase.m;
\[Omega]=\[Omega]Base; (* Next solve using base value of adjustment cost *)
SolvePolFunc;
InitializeSimData;
Do[AddOnePeriod,{PreShockPeriods}];
\[ScriptK]tList[[-1]]=Last[\[ScriptK]tList]0.50; (* 50% of the capital is lost*)
Do[AddOnePeriod,{AfterShockPeriods}];
SetOptions[ListPlot,PlotStyle->{Red,PointSize[Medium]}];
kDropCostAdjBase=GraphicsGrid[{
{\[ScriptK]TimeCostAdjBase=ListPlot[\[ScriptK]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptK]tList].95}],
\[Lambda]TimeCostAdjBase=ListPlot[\[Lambda]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[Lambda]\), \(t\)]\)"},AxesOrigin->{0,Min[\[Lambda]tList].95}]},{\[ScriptI]TimeCostAdjBase=ListPlot[\[ScriptI]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptI]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptI]tList].9}],\[ScriptC]TimeCostAdjBase=ListPlot[\[ScriptC]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptC]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptC]tList].95}]},{
\[DoubleStruckCapitalR]TimeCostAdjBase=ListPlot[\[DoubleStruckCapitalR]tp1List,AxesLabel->{"t","\!\(\*SubscriptBox[\(R\), \(t + 1\)]\)"},AxesOrigin->{0,Min[\[DoubleStruckCapitalR]tp1List].99}],\[ScriptJ]TimeCostAdjBase=ListPlot[\[ScriptJ]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptJ]\), \(t\)]\)"},AxesOrigin->{0,0}]
}},ImageSize->600];
SetOptions[ListPlot,PlotStyle->{Black,PointSize[Medium]}];
(*Print[kDropCostAdjBase];
Export["../../Figures/kDropCostAdjBase.pdf",kDropCostAdjBase];
Export["../../Figures/kDropCostAdjBase.eps",kDropCostAdjBase];
Export["../../Figures/kDropCostAdjBase.png",kDropCostAdjBase,ImageSize->{72 8.,72 8./GoldenRatio}];
*)



kDropCostAdj0VsBase=GraphicsGrid[{
{Show[\[ScriptK]TimeCostAdjBase,\[ScriptK]TimeCostAdj0],Show[\[Lambda]TimeCostAdjBase,\[Lambda]TimeCostAdj0]}
,{Show[\[ScriptI]TimeCostAdjBase,\[ScriptI]TimeCostAdj0],Show[\[ScriptC]TimeCostAdjBase,\[ScriptC]TimeCostAdj0]}
,{Show[\[DoubleStruckCapitalR]TimeCostAdjBase,\[DoubleStruckCapitalR]TimeCostAdj0],Show[\[ScriptJ]TimeCostAdjBase,\[ScriptJ]TimeCostAdj0]}
},ImageSize->600,PlotRange->All];
Print[kDropCostAdj0VsBase];



(* Level of investment falls because costs are scaled relative to level of k; ratio of i to k rises even with adj costs *)


Export["../../Figures/kDropCostAdj0VsBase.pdf",kDropCostAdj0VsBase];
Export["../../Figures/kDropCostAdj0VsBase.eps",kDropCostAdj0VsBase];
Export["../../Figures/kDropCostAdj0VsBase.png",kDropCostAdj0VsBase,ImageSize->{72 8.,72 8./GoldenRatio}];



<<qRamseyParamsBase.m;
SolvePolFunc;
InitializeSimData;
Do[AddOnePeriod,{PreShockPeriods}];
\[Delta]=0.10;
SolvePolFunc;
Do[AddOnePeriod,{AfterShockPeriods}];


SetOptions[ListPlot,PlotStyle->{Red,PointSize[Medium]}];
DeprRiseCostAdjBase=GraphicsGrid[{
{\[ScriptK]TimeCostAdjBase=ListPlot[\[ScriptK]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptK]tList].95}],
\[Lambda]TimeCostAdjBase=ListPlot[\[Lambda]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[Lambda]\), \(t\)]\)"},AxesOrigin->{0,Min[\[Lambda]tList].95}]},{\[ScriptI]TimeCostAdjBase=ListPlot[\[ScriptI]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptI]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptI]tList].9}],\[ScriptC]TimeCostAdjBase=ListPlot[\[ScriptC]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptC]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptC]tList].95}]},{
\[DoubleStruckCapitalR]TimeCostAdjBase=ListPlot[\[DoubleStruckCapitalR]tp1List,AxesLabel->{"t","\!\(\*SubscriptBox[\(R\), \(t + 1\)]\)"},AxesOrigin->{0,Min[\[DoubleStruckCapitalR]tp1List].99}],\[ScriptJ]TimeCostAdjBase=ListPlot[\[ScriptJ]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptJ]\), \(t\)]\)"},AxesOrigin->{0,0}]
}},ImageSize->600];
SetOptions[ListPlot,PlotStyle->{Black,PointSize[Medium]}];
(*Print[DeprRiseCostAdjBase];
Export["../../Figures/DeprRiseCostAdjBase.pdf",DeprRiseCostAdjBase];
Export["../../Figures/DeprRiseCostAdjBase.eps",DeprRiseCostAdjBase];
Export["../../Figures/DeprRiseCostAdjBase.png",DeprRiseCostAdjBase,ImageSize->{72 8.,72 8./GoldenRatio}];*)


<<qRamseyParamsBase.m;
\[Omega]=0;
Quiet[SolvePolFunc];
InitializeSimData;
Do[AddOnePeriod,{PreShockPeriods}];
\[Delta]=0.10;\[Omega]=0;
Quiet[SolvePolFunc];
Do[AddOnePeriod,{AfterShockPeriods}];


DeprRiseCostAdj0=GraphicsGrid[{
{\[ScriptK]TimeCostAdj0=ListPlot[\[ScriptK]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptK]tList].95}],
\[Lambda]TimeCostAdj0=ListPlot[\[Lambda]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[Lambda]\), \(t\)]\)"},AxesOrigin->{0,Min[\[Lambda]tList].95}]},{\[ScriptI]TimeCostAdj0=ListPlot[\[ScriptI]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptI]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptI]tList].9}],\[ScriptC]TimeCostAdj0=ListPlot[\[ScriptC]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptC]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptC]tList].95}]},{
\[DoubleStruckCapitalR]TimeCostAdj0=ListPlot[\[DoubleStruckCapitalR]tp1List,AxesLabel->{"t","\!\(\*SubscriptBox[\(R\), \(t + 1\)]\)"},AxesOrigin->{0,Min[\[DoubleStruckCapitalR]tp1List].99}],\[ScriptJ]TimeCostAdj0=ListPlot[\[ScriptJ]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptJ]\), \(t\)]\)"},AxesOrigin->{0,0}]
}},ImageSize->600];(*
Print[DeprRiseCostAdj0];
Export["../../Figures/DeprRiseCostAdj0.pdf",DeprRiseCostAdj0];
Export["../../Figures/DeprRiseCostAdj0.eps",DeprRiseCostAdj0];
Export["../../Figures/DeprRiseCostAdj0.png",DeprRiseCostAdj0,ImageSize->{72 8.,72 8./GoldenRatio}];*)


DeprRiseCostAdj0VsBase=GraphicsGrid[{
{Show[\[ScriptK]TimeCostAdjBase,\[ScriptK]TimeCostAdj0],Show[\[Lambda]TimeCostAdjBase,\[Lambda]TimeCostAdj0]}
,{Show[\[ScriptI]TimeCostAdjBase,\[ScriptI]TimeCostAdj0],Show[\[ScriptC]TimeCostAdjBase,\[ScriptC]TimeCostAdj0]}
,{Show[\[DoubleStruckCapitalR]TimeCostAdjBase,\[DoubleStruckCapitalR]TimeCostAdj0],Show[\[ScriptJ]TimeCostAdjBase,\[ScriptJ]TimeCostAdj0]}
},ImageSize->600,PlotRange->All];
Print[DeprRiseCostAdj0VsBase];
Export["../../Figures/DeprRiseCostAdj0VsBase.pdf",DeprRiseCostAdj0VsBase];
Export["../../Figures/DeprRiseCostAdj0VsBase.eps",DeprRiseCostAdj0VsBase];
Export["../../Figures/DeprRiseCostAdj0VsBase.png",DeprRiseCostAdj0VsBase,ImageSize->{72 8.,72 8./GoldenRatio}];




<<qRamseyParamsBase.m;
SolvePolFunc;
InitializeSimData;
Do[AddOnePeriod,{PreShockPeriods}];
\[Beta]=0.94;
SolvePolFunc;
Do[AddOnePeriod,{AfterShockPeriods}];


PatDropBase=GraphicsGrid[{
{\[ScriptK]TimeAdjCost0=ListPlot[\[ScriptK]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\)"},AxesOrigin->{0,0. Min[\[ScriptK]tList].95}],
\[Lambda]TimeAdjCost0=ListPlot[\[Lambda]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[Lambda]\), \(t\)]\)"},AxesOrigin->{0,Min[\[Lambda]tList].95}]},
{\[ScriptI]TimeAdjCost0=ListPlot[\[ScriptI]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptI]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptI]tList].9}],
\[ScriptC]TimeAdjCost0=ListPlot[\[ScriptC]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptC]\), \(t\)]\)"},AxesOrigin->{0,0.Min[\[ScriptC]tList].95}]},{\[DoubleStruckCapitalR]TimeAdjCost0=ListPlot[\[DoubleStruckCapitalR]tp1List,AxesLabel->{"t","\!\(\*SubscriptBox[\(R\), \(t + 1\)]\)"},AxesOrigin->{0,Min[\[DoubleStruckCapitalR]tp1List].99}],\[ScriptJ]TimeAdjCost0=ListPlot[\[ScriptJ]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptJ]\), \(t\)]\)"},AxesOrigin->{0,0}]
}},ImageSize->600];
Print[PatDropBase];


Export["../../Figures/PatDrop.pdf",PatDropBase];
Export["../../Figures/PatDrop.eps",PatDropBase];
Export["../../Figures/PatDrop.png",PatDropBase,ImageSize->{72 8.,72 8./GoldenRatio}];
