(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



ClearAll["Global`*"];
SetDirectory[NotebookDirectory[]];
Get["./DiscreteApproxToMeanOneLogNormal.m"];
\[Omega]Hat=(\[Sigma]\[Theta]2/\[Sigma]\[Theta]1)\[Omega];\[Zeta]=0.5 \[Omega]Hat(1-\[Omega]Hat) \[Sigma]\[Theta]1^2;
\[Theta]1Mean=-0.5 \[Sigma]\[Theta]1^2;
\[Theta]2Mean=-0.5 \[Sigma]\[Theta]2^2;
\[ScriptR]Mean=\[Theta]2Mean+\[ScriptR]Prm+rFree+\[Omega]Hat \[Theta]1Mean + \[Zeta];
\[Theta]1MinPlot=\[Theta]1Mean-StdDevPlotRange \[Sigma]\[Theta]1;
\[Theta]1MaxPlot=\[Theta]1Mean+StdDevPlotRange \[Sigma]\[Theta]1;
\[Theta]2MinPlot=\[Theta]2Mean-StdDevPlotRange \[Sigma]\[Theta]2;
\[Theta]2MaxPlot=\[Theta]2Mean+StdDevPlotRange \[Sigma]\[Theta]2;
\[ScriptR]MinPlot=\[ScriptR]Prm+rFree+\[Omega]Hat \[Theta]1MinPlot+\[Zeta]+\[Theta]2MinPlot;
\[ScriptR]MaxPlot=\[ScriptR]Prm+rFree+\[Omega]Hat \[Theta]1MaxPlot+\[Zeta]+\[Theta]2MaxPlot;
StdDevPlotRange=3.0;


\[ScriptR]Prm=rFree=0.02;
\[Sigma]\[Theta]2=\[Sigma]\[Theta]1=0.2;


Clear[\[Theta]1,\[Theta]2];
\[Omega]=0.5;
Print[
Expectation[{Exp[\[Theta]1],Exp[\[Zeta] + \[Omega]Hat \[Theta]1 + \[Theta]2]},{\[Theta]1,\[Theta]2}\[Distributed]MultinormalDistribution[{-0.5 \[Sigma]\[Theta]1^2,-0.5 \[Sigma]\[Theta]2^2},{{\[Sigma]\[Theta]1^2,0},{0,\[Sigma]\[Theta]2^2}}]]];
Clear[\[Theta]1,\[Theta]2,\[Omega]];



JointCDF[\[Theta]1_,\[ScriptR]_,\[Omega]_]:=Block[{\[Omega]Hat=(\[Sigma]\[Theta]2/\[Sigma]\[Theta]1)\[Omega],\[Zeta]},
\[Zeta]=0.5 \[Omega]Hat(1-\[Omega]Hat) \[Sigma]\[Theta]1^2;CDF[MultinormalDistribution[{-0.5 \[Sigma]\[Theta]1^2,-0.5 \[Sigma]\[Theta]2^2},{{\[Sigma]\[Theta]1^2,0},{0,\[Sigma]\[Theta]2^2}}]
,{\[Theta]1,\[ScriptR]-\[ScriptR]Prm-rFree-\[Omega]Hat \[Theta]1-\[Zeta]}]];
JointPDF[\[Theta]1_,\[ScriptR]_,\[Omega]_]:=Block[{\[Omega]Hat=(\[Sigma]\[Theta]2/\[Sigma]\[Theta]1)\[Omega],\[Zeta]},
\[Zeta]=0.5 \[Omega]Hat(1-\[Omega]Hat) \[Sigma]\[Theta]1^2;PDF[MultinormalDistribution[{-0.5 \[Sigma]\[Theta]1^2,-0.5 \[Sigma]\[Theta]2^2},{{\[Sigma]\[Theta]1^2,0},{0,\[Sigma]\[Theta]2^2}}]
,{\[Theta]1,\[ScriptR]-\[ScriptR]Prm-rFree-\[Omega]Hat \[Theta]1-\[Zeta]}]];


\[Omega]=0.;Print[JointCDF[\[Theta]1Mean,\[ScriptR]Mean,\[Omega]]];


Print[Plot3D[JointCDF[\[Theta]1Plot,\[Theta]2Plot+(\[ScriptR]Prm+rFree+\[Omega]Hat \[CurlyTheta]+\[Zeta]),\[Omega]]
,{\[Theta]1Plot,\[Theta]1MinPlot,\[Theta]1MaxPlot}
,{\[Theta]2Plot,\[Theta]2MinPlot,\[Theta]2MaxPlot}
,AxesLabel->{"\[Theta]1","\[Theta]2","CDF"}]];


\[Omega]=0.0;
Print[
\[Omega]0p0True=Plot3D[JointCDF[\[Theta]1Plot,\[ScriptR]Plot,\[Omega]]
,{\[Theta]1Plot,-0.5 \[Sigma]\[Theta]1^2-StdDevPlotRange \[Sigma]\[Theta]1,-0.5 \[Sigma]\[Theta]1^2+StdDevPlotRange \[Sigma]\[Theta]1}
,{\[ScriptR]Plot,-0.5 \[Sigma]\[Theta]2^2+\[ScriptR]Prm+rFree-StdDevPlotRange \[Sigma]\[Theta]2,-0.5 \[Sigma]\[Theta]2^2+\[ScriptR]Prm+rFree+StdDevPlotRange \[Sigma]\[Theta]2},AxesLabel->{"\!\(\*SubscriptBox[\(\[Theta]\), \(1\)]\)","\[ScriptR]","CDF"}]];
Clear[\[Omega]];


\[Omega]=0.5;
Print[
\[Omega]0p5True=Plot3D[JointCDF[\[Theta]1Plot,\[ScriptR]Plot,\[Omega]]
,{\[Theta]1Plot,\[Theta]1MinPlot,\[Theta]1MaxPlot}
,{\[ScriptR]Plot,\[ScriptR]MinPlot,\[ScriptR]MaxPlot},AxesLabel->{"\!\(\*SubscriptBox[\(\[Theta]\), \(1\)]\)","\[ScriptR]","CDF"}]];
Clear[\[Omega]];


Print[\[Omega]0to1Plots=Table[Plot3D[JointPDF[\[Theta]1Plot,\[ScriptR]Plot,\[Omega]],{\[Theta]1Plot,-0.5 \[Sigma]\[Theta]1^2-StdDevPlotRange \[Sigma]\[Theta]1,-0.5 \[Sigma]\[Theta]1^2+StdDevPlotRange \[Sigma]\[Theta]1},{\[ScriptR]Plot,-0.5 \[Sigma]\[Theta]2^2+\[ScriptR]Prm+rFree-StdDevPlotRange \[Sigma]\[Theta]2,-0.5 \[Sigma]\[Theta]2^2+\[ScriptR]Prm+rFree+StdDevPlotRange \[Sigma]\[Theta]2},AxesLabel->{"\!\(\*SubscriptBox[\(\[Theta]\), \(1\)]\)","\[ScriptR]","PDF"}],{\[Omega],0,1,0.1}]];


ListAnimate[\[Omega]0to1Plots]


NumOfPoints=15;
{\[CapitalTheta]1Pts,\[CapitalTheta]1Prb,\[CapitalTheta]1EdgesOuter,\[CapitalTheta]1CDFOuter,\[CapitalTheta]1EdgesInner,\[CapitalTheta]1CDFInner} = DiscreteApproxToMeanOneLogNormalWithEdges[\[Sigma]\[Theta]1,NumOfPoints];
{\[CapitalTheta]2Pts,\[CapitalTheta]2Prb,\[CapitalTheta]2EdgesOuter,\[CapitalTheta]2CDFOuter,\[CapitalTheta]2EdgesInner,\[CapitalTheta]2CDFInner} = DiscreteApproxToMeanOneLogNormalWithEdges[\[Sigma]\[Theta]2,NumOfPoints];

\[Omega]=0.0;

CDFEdgePoints\[Theta]1\[ScriptR]=CDFEdgePoints\[CapitalTheta]1\[CapitalTheta]2=CDFEdgePoints\[Theta]1\[Theta]2={};
Do[
AppendTo[CDFEdgePoints\[CapitalTheta]1\[CapitalTheta]2,{\[CapitalTheta]1EdgesInner[[i]],\[CapitalTheta]2EdgesInner[[j]],\[CapitalTheta]1CDFInner[[i]]\[CapitalTheta]2CDFInner[[j]]}];AppendTo[CDFEdgePoints\[Theta]1\[Theta]2,{Log[\[CapitalTheta]1EdgesInner[[i]]],Log[\[CapitalTheta]2EdgesInner[[j]]],\[CapitalTheta]1CDFInner[[i]]\[CapitalTheta]2CDFInner[[j]]}];
AppendTo[CDFEdgePoints\[Theta]1\[ScriptR],{\[CurlyTheta]=Log[\[CapitalTheta]1EdgesInner[[i]]],Log[\[CapitalTheta]2EdgesInner[[j]]]+\[ScriptR]Prm+rFree+\[Omega]Hat \[CurlyTheta]+\[Zeta],\[CapitalTheta]1CDFInner[[i]]\[CapitalTheta]2CDFInner[[j]]}]
,{i,Length[\[CapitalTheta]1EdgesInner]},{j,Length[\[CapitalTheta]2EdgesInner]}];

CDFEdgePoints\[Theta]1\[ScriptR]Plot=ListPointPlot3D[CDFEdgePoints\[Theta]1\[ScriptR]];CDFEdgePoints\[Theta]1\[Theta]2Plot=ListPointPlot3D[CDFEdgePoints\[Theta]1\[Theta]2];
CDFTrue\[Theta]1\[Theta]2=Plot3D[JointCDF[\[Theta]1Plot,\[Theta]2Plot+(\[ScriptR]Prm+rFree+\[Omega]Hat \[Theta]1Plot+\[Zeta]),\[Omega]]
,{\[Theta]1Plot,\[Theta]1MinPlot,\[Theta]1MaxPlot}
,{\[Theta]2Plot,\[Theta]2MinPlot,\[Theta]2MaxPlot}
,AxesLabel->{"\[Theta]1","\[Theta]2","CDF"}];
CDFTrue\[Theta]1\[ScriptR]=Plot3D[JointCDF[\[Theta]1Plot,\[ScriptR]Plot,\[Omega]]
,{\[Theta]1Plot,\[Theta]1MinPlot,\[Theta]1MaxPlot}
,{\[ScriptR]Plot,\[ScriptR]MinPlot,\[ScriptR]MaxPlot}
,AxesLabel->{"\!\(\*SubscriptBox[\(\[Theta]\), \(1\)]\)","\[ScriptR]","CDF"}];
Print[CDF\[Theta]1\[ScriptR]Plot=Show[CDFTrue\[Theta]1\[ScriptR],CDFEdgePoints\[Theta]1\[ScriptR]Plot]];Print[CDF\[Theta]1\[Theta]2Plot=Show[CDFTrue\[Theta]1\[Theta]2,CDFEdgePoints\[Theta]1\[Theta]2Plot]];



\[Omega]=0.5;
CDFMidPoints\[Theta]1\[ScriptR]=CDFMidPoints\[CapitalTheta]1\[CapitalTheta]2=CDFMidPoints\[Theta]1\[Theta]2={};
Do[
AppendTo[CDFMidPoints\[CapitalTheta]1\[CapitalTheta]2,{\[CapitalTheta]1Pts[[i]],\[CapitalTheta]2Pts[[j]],\[CapitalTheta]1CDFOuter[[i]]\[CapitalTheta]2CDFOuter[[j]]+(\[CapitalTheta]1CDFOuter[[i+1]]\[CapitalTheta]2CDFOuter[[j+1]]-\[CapitalTheta]1CDFOuter[[i]]\[CapitalTheta]2CDFOuter[[j]])/2}];AppendTo[CDFMidPoints\[Theta]1\[Theta]2,{Log[\[CapitalTheta]1Pts[[i]]],Log[\[CapitalTheta]2Pts[[j]]],\[CapitalTheta]1CDFOuter[[i]]\[CapitalTheta]2CDFOuter[[j]]+(\[CapitalTheta]1CDFOuter[[i+1]]\[CapitalTheta]2CDFOuter[[j+1]]-\[CapitalTheta]1CDFOuter[[i]]\[CapitalTheta]2CDFOuter[[j]])/2}];
AppendTo[CDFMidPoints\[Theta]1\[ScriptR],{\[CurlyTheta]=Log[\[CapitalTheta]1Pts[[i]]],Log[\[CapitalTheta]2Pts[[j]]]+\[ScriptR]Prm+rFree+\[Omega]Hat \[CurlyTheta]+\[Zeta],\[CapitalTheta]1CDFOuter[[i]]\[CapitalTheta]2CDFOuter[[j]]+(\[CapitalTheta]1CDFOuter[[i+1]]\[CapitalTheta]2CDFOuter[[j+1]]-\[CapitalTheta]1CDFOuter[[i]]\[CapitalTheta]2CDFOuter[[j]])/2}]
,{i,Length[\[CapitalTheta]1Pts]},{j,Length[\[CapitalTheta]2Pts]}];

CDFMidPoints\[Theta]1\[ScriptR]Plot=ListPointPlot3D[CDFMidPoints\[Theta]1\[ScriptR],PlotStyle->Red];
CDFMidPoints\[Theta]1\[Theta]2Plot=ListPointPlot3D[CDFMidPoints\[Theta]1\[Theta]2,PlotStyle->Red];

CDFTrue\[Theta]1\[Theta]2=Plot3D[JointCDF[\[Theta]1Plot,\[Theta]2Plot+(\[ScriptR]Prm+rFree+\[Omega]Hat \[Theta]1Plot+\[Zeta]),\[Omega]]
,{\[Theta]1Plot,\[Theta]1MinPlot,\[Theta]1MaxPlot}
,{\[Theta]2Plot,\[Theta]2MinPlot,\[Theta]2MaxPlot}
,AxesLabel->{"\[Theta]1","\[Theta]2","CDF"}];
CDFTrue\[Theta]1\[ScriptR]=Plot3D[JointCDF[\[Theta]1Plot,\[ScriptR]Plot,\[Omega]]
,{\[Theta]1Plot,\[Theta]1MinPlot,\[Theta]1MaxPlot}
,{\[ScriptR]Plot,\[ScriptR]MinPlot,\[ScriptR]MaxPlot}
,AxesLabel->{"\[Theta]1","\[ScriptR]","CDF"}];
CDF\[Theta]1\[ScriptR]Plot=Show[CDFTrue\[Theta]1\[ScriptR],CDFMidPoints\[Theta]1\[ScriptR]Plot];CDF\[Theta]1\[Theta]2Plot=Show[CDFTrue\[Theta]1\[Theta]2,CDFMidPoints\[Theta]1\[Theta]2Plot];
CDF\[Theta]1\[ScriptR]Plot


Export["../../Figures/CDFPlot.pdf",CDF\[Theta]1\[ScriptR]Plot];
Export["../../Figures/CDFPlot.png",CDF\[Theta]1\[ScriptR]Plot,ImageSize->{72 8.,72 8./GoldenRatio}];
Export["../../Figures/CDFPlot.svg",CDF\[Theta]1\[ScriptR]Plot];
