(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



<<SetupEnvironment.m; (* Preferences like font sizes etc *)
<<EntrepreneurPFfunctions.m ;     (* loading functions *)
<<EntrepreneurPFparams.m ;            (* loading parameters *)



SolvePolFunc;(* solving the the unconstrained policy functions *)


(* Value of the profit maximizing firm *)
MaxPlotRange=\[ScriptK]SS+\[ScriptK]SS/5;
Print[Plot[\[ScriptE]Soln[\[ScriptK]Plot],{\[ScriptK]Plot,0,MaxPlotRange}
,AxesLabel->{"\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\)","\!\(\*SubscriptBox[\(\[ScriptE]\), \(t\)]\)(\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\))"},Ticks->{{{\[ScriptK]SS,"\!\(\*SubscriptBox[\(\[ScriptK]\), \(SS\)]\)"}},None}
]];


MaxPlotRange=\[ScriptK]SS+\[ScriptK]SS/5;
\[ScriptM]=1;
Print[PolFuncPlot=Show[Plot[{\[Iota]Soln[\[ScriptK]Plot]\[ScriptK]Plot,\[ScriptC]Func[\[ScriptM],\[ScriptK]Plot],\[ScriptJ]Soln[\[ScriptK]Plot],\[ScriptA]Soln[\[ScriptM],\[ScriptK]Plot]}
,{\[ScriptK]Plot,0,MaxPlotRange}
,PlotStyle->{{Thick,Red},{Thick,Darker[Green]},{Thick,Black},{Thick,Blue}}
,AxesLabel->{"\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\)\!\(\*SubscriptBox[\(|\), \(\*SubscriptBox[\(\[ScriptM]\), \(t\)] = 1\)]\)"},Ticks->{{{\[ScriptK]SS,"\!\(\*SubscriptBox[\(\[ScriptK]\), \(SS\)]\)"}},Automatic}],
Graphics[{
Text["\!\(\*SubscriptBox[\(\[ScriptC]\), \(t\)]\)",{2.6,.9}],Text[Style["\[UpperRightArrow]",Large],{2.7,1.}],
Text["\!\(\*SubscriptBox[\(\[ScriptA]\), \(t\)]\)",{2.6,-.3}],Text[Style["\[LowerRightArrow]",Large],{2.7,-.45}], (* Subscript[\[ScriptA], t]=Subscript[\[ScriptM], t]-Subscript[\[ScriptC], t]-Subscript[\[ScriptI], t]-Subscript[\[ScriptJ], t]*)
Text["\!\(\*SubscriptBox[\(\[Iota]\), \(t\)]\) \!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\) = \!\(\*SubscriptBox[\(\[ScriptI]\), \(t\)]\)-(\[Delta]/\[Dalet])\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\)",{2.9,.5}],Text[Style["\[LowerLeftArrow]",Large],{2.7,.3}],
Text["\!\(\*SubscriptBox[\(\[ScriptJ]\), \(t\)]\)",{1.2,.3}],Text[Style["\[LowerLeftArrow]",Large],{1,.2}]}]]];


Print[lPhaseDiag=
Show[
    Plot[{\[Lambda]Saddle[\[ScriptK]Plot],\[CapitalDelta]\[ScriptK]Equals0In\[Lambda]Space[\[ScriptK]Plot],\[CapitalDelta]\[Lambda]Equals0[\[ScriptK]Plot]},{\[ScriptK]Plot,\[ScriptK]SS 0.5,1.5\[ScriptK]SS}
    ,AxesOrigin->{\[ScriptK]SS 0.5,0.2},Ticks->{{{\[ScriptK]SS,"\!\(\*OverscriptBox[\(\[ScriptK]\), \(\[Hacek]\)]\)"}},{{\[ScriptCapitalP] \[GothicCapitalR]/\[Dalet],"\!\(\*FractionBox[\(\[ScriptCapitalP]\\\ R\), \(\[Dalet]\)]\)"}}}
    ,PlotStyle->{Black,{Dashed,Black},{Dashed,Black}},AxesLabel->{"\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\)","\!\(\*SubscriptBox[\(\[Lambda]\), \(t\)]\)"},PlotRange->All],
Graphics[{
Text["\!\(\*SubscriptBox[\(\[DoubleStruckCapitalE]\), \(t\)]\)[\!\(\*SubscriptBox[\(\[CapitalDelta]\[Lambda]\), \(t + 1\)]\)]=0",{2.8,1.9}],Text[Style["\[LowerLeftArrow]",Large],{2.6,1.7}],
Text["saddle path",{4.6,1.3}],Text[Style["\[LowerLeftArrow]",Large],{4.5,1.18}],
Text["\!\(\*SubscriptBox[\(\[CapitalDelta]\[ScriptK]\), \(t + 1\)])=0",{2.5,.8}],Text[Style["\[UpperRightArrow]",Large],{2.7,1}]}]]];


Export["../../Figures/lPhaseDiag.pdf",lPhaseDiag];
Export["../../Figures/lPhaseDiag.eps",lPhaseDiag];
Export["../../Figures/lPhaseDiag.png",lPhaseDiag,ImageSize->72 9];


Print[qPhaseDiag=Show[
Plot[{\[Koppa]Saddle[\[ScriptK]Plot],\[CapitalDelta]\[ScriptK]Equals0In\[Koppa]Space[\[ScriptK]Plot],\[CapitalDelta]\[Koppa]0[\[ScriptK]Plot]},{\[ScriptK]Plot,\[ScriptK]SS .5,1.5\[ScriptK]SS},AxesOrigin->{\[ScriptK]SS .5,0},Ticks->{{{\[ScriptK]SS,"\!\(\*OverscriptBox[\(\[ScriptK]\), \(\[Hacek]\)]\)"}},{{1,1}}},PlotStyle->{Black,{Dashed,Black},{Dashed,Black}},AxesLabel->{"\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\)","\!\(\*SubscriptBox[\(\[Koppa]\), \(t\)]\)"}],
Graphics[{
Text["\!\(\*SubscriptBox[\(\[DoubleStruckCapitalE]\), \(t\)]\)[\!\(\*SubscriptBox[\(\[CapitalDelta]\[Koppa]\), \(t + 1\)]\)]=0",{2.8,1.7}],Text[Style["\[LowerLeftArrow]",Large],{2.6,1.5}],
Text["saddle path",{4.6,1.15}],Text[Style["\[LowerLeftArrow]",Large],{4.5,1.02}],
Text["\!\(\*SubscriptBox[\(\[CapitalDelta]\[ScriptK]\), \(t + 1\)])=0",{2.5,.7}],Text[Style["\[UpperRightArrow]",Large],{2.7,.9}]}]]];


Export["../../Figures/qPhaseDiag.pdf",qPhaseDiag];
Export["../../Figures/qPhaseDiag.eps",qPhaseDiag];
Export["../../Figures/qPhaseDiag.png",qPhaseDiag,ImageSize->72 9];


PreShockPeriods=5;
AfterShockPeriods=30;


Initialize:=Block[{},\[ScriptA]tm1=10;\[ScriptK]tList={\[ScriptK]SS};\[ScriptM]tList={(1-\[Tau])(\[ScriptCapitalW][\[ScriptK]SS]+\[ScriptF]'[\[ScriptK]SS])+\[ScriptA]tm1 \[GothicCapitalR]};\[ScriptC]tList=\[ScriptA]tList=\[ScriptI]tList={};];


AddOnePeriod:=Block[{},
AppendTo[\[ScriptC]tList,\[ScriptC]Func[Last[\[ScriptM]tList],Last[\[ScriptK]tList]]];
AppendTo[\[ScriptA]tList,\[ScriptA]Soln[Last[\[ScriptM]tList],Last[\[ScriptK]tList]]];
AppendTo[\[ScriptI]tList,\[ScriptI]Soln[Last[\[ScriptK]tList]]];
AppendTo[\[ScriptK]tList,\[Dalet](Last[\[ScriptK]tList]+Last[\[ScriptI]tList])];
AppendTo[\[ScriptM]tList,(1-\[Tau])(\[ScriptCapitalW][Last[\[ScriptK]tList]]+Last[\[ScriptK]tList] \[ScriptF]'[Last[\[ScriptK]tList]])+Last[\[ScriptA]tList] \[GothicCapitalR]];
];


Initialize;
(* Simulation *)
Do[AddOnePeriod,{PreShockPeriods}];
\[ScriptM]tList[[-1]]=0; (* total loss of monetary resources *)
Do[AddOnePeriod,{AfterShockPeriods}];


Print[mlossIRF=GraphicsGrid[{
{ListPlot[\[ScriptM]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptM]\), \(t\)]\)"},Ticks->{{},{0}},AxesOrigin->{0,0}],ListPlot[\[ScriptK]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\)"},Ticks->{{},{0,{\[ScriptK]SS,"\!\(\*OverscriptBox[\(\[ScriptK]\), \(\[Hacek]\)]\)"}}}]},
{ListPlot[\[ScriptC]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptC]\), \(t\)]\)"},Ticks->{{},{0}},AxesOrigin->{0,0}],
ListPlot[\[ScriptI]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptI]\), \(t\)]\)"},Ticks->{{},{0}},AxesOrigin->{0,0}]}
},ImageSize->600]];


Export["../../Figures/mlossIRF.pdf",mlossIRF];
Export["../../Figures/mlossIRF.eps",mlossIRF];
Export["../../Figures/mlossIRF.png",mlossIRF,ImageSize->72 9];


Initialize;
(* Simulation *)
Do[AddOnePeriod,{PreShockPeriods}];
\[ScriptK]tList[[-1]]=\[ScriptK]tList[[-1]]0.5; (* partial loss of capital *)
Do[AddOnePeriod,{AfterShockPeriods}];


Print[klossIRF=GraphicsGrid[{
{ListPlot[\[ScriptM]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptM]\), \(t\)]\)"},Ticks->{{},{0}},AxesOrigin->{0,0}],ListPlot[\[ScriptK]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptK]\), \(t\)]\)"},Ticks->{{},{0,{\[ScriptK]SS,"\!\(\*OverscriptBox[\(\[ScriptK]\), \(\[Hacek]\)]\)"}}},AxesOrigin->{0,0}]},
{ListPlot[\[ScriptC]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptC]\), \(t\)]\)"},Ticks->{{},{0}},AxesOrigin->{0,0}],
ListPlot[\[ScriptI]tList,AxesLabel->{"t","\!\(\*SubscriptBox[\(\[ScriptI]\), \(t\)]\)"},Ticks->{{},{0}},AxesOrigin->{0,0}]}
},ImageSize->600]];


Export["../../Figures/klossIRF.pdf",klossIRF];
Export["../../Figures/klossIRF.eps",klossIRF];
Export["../../Figures/klossIRF.png",klossIRF,ImageSize->72 9];
