(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



FrontEndExecute[FrontEndToken["DeleteGeneratedCells"]]


ClearAll["Global`*"];SetDirectory[NotebookDirectory[]];Get["./DefinitionsAndAssumptions.m"];ClearVars;
ShowVariableDefinitions;



ClearVars;
\[DoubleStruckCapitalE]\[GothicCapitalR]ToTheOneMinusRhoExact[\[Stigma]_,\[Sigma]_,\[Rho]_]:= 
    NIntegrate[PDF[LogNormalDistribution[\[ScriptR]-\[Sigma]^2/2,\[Sigma]],\[ScriptCapitalR]tp1](Rfree +(\[ScriptCapitalR]tp1-Rfree)\[Stigma])^(1-\[Rho]) 
,{\[ScriptCapitalR]tp1,Exp[\[ScriptR]-\[Sigma]^2/2- 10 \[Sigma]],Exp[\[ScriptR]-\[Sigma]^2/2+ 10 \[Sigma]]}]; (* In principle, integration should be from 0. to \[Infinity]; in practice, Mathematica has trouble with this, so integrate over 10 standard deviation range *)
\[Kappa]Exact[\[Sigma]_,\[Rho]_] := 1- (\[Beta] \[DoubleStruckCapitalE]\[GothicCapitalR]ToTheOneMinusRhoExact[\[Stigma]OptExact[\[Sigma],\[Rho]],\[Sigma],\[Rho]])^(1/\[Rho]);
\[Kappa]Approx[\[Sigma]_,\[Rho]_] := \[Rho]^-1 \[CurlyTheta]+(1-\[Rho]^-1)(rfree+(\[Phi]^2/(2\[Rho] \[Sigma]^2)));
\[DoubleStruckCapitalE]\[GothicR]For\[Stigma]Approx[\[Sigma]_,\[Rho]_]:= Block[{\[Stigma]OptVal},\[Stigma]OptVal=\[Stigma]OptApprox[\[Sigma],\[Rho]];rfree+\[Stigma]OptVal \[Phi]+\[Stigma]OptVal(1-\[Stigma]OptVal)\[Sigma]^2/2];
\[DoubleStruckCapitalE]\[GothicR]For\[Stigma]Exact[\[Sigma]_,\[Rho]_]:= Block[{\[Stigma]OptVal},\[Stigma]OptVal=\[Stigma]OptExact[\[Sigma],\[Rho]];rfree+\[Stigma]OptVal \[Phi]+\[Stigma]OptVal(1-\[Stigma]OptVal)\[Sigma]^2/2];
\[Sigma]Where\[Stigma]ApproxHits1[\[Phi]_,\[Rho]_]:=  (\[Phi]/\[Rho])^0.5;
\[Rho]Where\[Stigma]ApproxHits1[\[Phi]_,\[Sigma]_] := \[Phi]/\[Sigma]^2;


(* Since portfolio share invested in high-return asset declines with riskiness, so does portfolio return *)
ClearVars;
\[ScriptR]=0.05;Rfree=Exp[rfree=0.02];\[Phi]=\[ScriptR]-rfree;
\[Sigma]Min=\[Sigma]Where\[Stigma]ApproxHits1[\[Phi],\[Rho]=3];(* The numerical integration breaks down when approximated portfolio share gets too large; so don't go there *)
(* Show that expected log portfolio returns are very close using approximation and exact *)
Off[NIntegrate::inumr];Print[Plot[{\[DoubleStruckCapitalE]\[GothicR]GivenOpt\[Stigma]Approx[\[Sigma]Plot,\[Rho]=3],\[DoubleStruckCapitalE]\[GothicR]GivenOpt\[Stigma]Exact[\[Sigma]Plot,\[Rho]=3]},{\[Sigma]Plot,\[Sigma]Min,2 \[Sigma]Min}
,PlotStyle->{{Red,Thickness[0.001]},{Black,Thickness[0.001]}}
,AxesLabel->{"\[Sigma]","\[DoubleStruckCapitalE]\[GothicR]"}
  ,PlotLabel->"Expected portfolio return for r = "<>ToString[rfree]<>", \[Phi] = "<>ToString[\[Phi]]<>", \[Rho] = "<>ToString[\[Rho]]
]];On[NIntegrate::inumr];
ClearVars;



(* MPC also declines, because income+substitution effects outweigh precautionary *)
ClearVars;
\[ScriptR]=0.05;Rfree=Exp[rfree=0.02];\[Beta]=Exp[-(\[CurlyTheta]=0.02)];\[Phi]=\[ScriptR]-rfree;
Off[NIntegrate::inumr];
Print[MPCApproxVsExactVsSigma = Plot[{\[Kappa]Exact[\[Sigma]Plot,\[Rho]=3],\[Kappa]Approx[\[Sigma]Plot,\[Rho]=3]}
,{\[Sigma]Plot,\[Sigma]Min,2 \[Sigma]Min}
,PlotStyle->{Black,Red}
,AxesLabel->{"\!\(\*
StyleBox[\"\[Sigma]\",\nFontSize->16]\)","\!\(\*
StyleBox[\"\[Kappa]\",\nFontSize->16]\)"}
,PlotLegend->{"Exact","Approx"}
,LegendSize->0.75
,LegendTextSpace->5
,LegendPosition->{0.,0.}
]];
Export["../../Figures/MPCApproxVsExactVsSigma.pdf",MPCApproxVsExactVsSigma];
Export["../../Figures/MPCApproxVsExactVsSigma.png",MPCApproxVsExactVsSigma,ImageSize->72 9];
Export["../../Figures/MPCApproxVsExactVsSigma.svg",MPCApproxVsExactVsSigma];
On[NIntegrate::inumr];
ClearVars;




\[ScriptR]=0.05;Rfree=Exp[rfree=0.02];\[Beta]=Exp[-(\[CurlyTheta]=0.02)];\[Phi]=\[ScriptR]-rfree;Print[MPCApproxVsExactVsRho=Plot[{\[Kappa]Exact[\[Sigma]=0.2,\[Rho]Plot],\[Kappa]Approx[\[Sigma]=0.2,\[Rho]Plot],PlotStyle->{Black,Red}}
,{\[Rho]Plot,1.001,2}
,AxesLabel->{"\!\(\*
StyleBox[\"\[Rho]\",\nFontSize->16]\)","\!\(\*
StyleBox[\"\[Kappa]\",\nFontSize->16]\)"}
,PlotLabel->"For \[ScriptR] = "<>ToString[\[ScriptR]]<>", r = "<>ToString[rfree]<>",\[Phi] = "<>ToString[\[Phi]]<>", \[Sigma] = "<>ToString[\[Sigma]]
]];
Export["../../Figures/MPCApproxVsExactVsRho.pdf",MPCApproxVsExactVsRho];
Export["../../Figures/MPCApproxVsExactVsRho.png",MPCApproxVsExactVsRho,ImageSize->72 9];
Export["../../Figures/MPCApproxVsExactVsRho.svg",MPCApproxVsExactVsRho];



FrontEndExecute[FrontEndToken["DeleteGeneratedCells"]]
