(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(* Initialization stuff; of no intrinsic interest *)
ClearAll["Global`*"];
If[Length[$FrontEnd] > 0,NBDir=SetDirectory[NotebookDirectory[]]];(* If running from the Notebook interface *)
(* If running from shell, must start from inside same directory in which notebook resides *)
If[$VersionNumber<8,(*then*) Print["These programs require Mathematica version 8 or greater."];Abort[]];
(* Method of displaying figures depends on whether being run in batch mode or interactively *)
If[$FrontEnd == Null,OpenFigsUsingShell=True,OpenFigsUsingShell=False]; 
(* Current working directory should correspond to appropriate location now whether running from shell or notebook *)
Get["/Volumes/Data/Code/Mathematica/Autoload/init.m"];



(* ::Input::Initialization:: *)
\[ScriptR]=0.05;
\[ScriptCapitalR]=1+\[ScriptR];
\[ScriptP]=1.;
\[ScriptA]Bar=\[ScriptA]=\[ScriptB]Bar=\[ScriptB]={0.,0.};
\[ScriptM]Bar=\[ScriptM]=\[ScriptC]Bar=\[ScriptC]=\[ScriptC]Rat={1.,1.};
\[ScriptX]=\[ScriptX]Bar={0.,0.};
\[Lambda]=0.5;
AddPeriod[\[Theta]Val_]:=Block[{},
AppendTo[\[ScriptB],\[ScriptCapitalR] Last[\[ScriptA]]];
AppendTo[\[ScriptB]Bar,\[ScriptCapitalR] Last[\[ScriptA]Bar]];
AppendTo[\[ScriptX],\[ScriptB][[-1]]+\[ScriptP] (\[Theta]Val-1)];
AppendTo[\[ScriptX]Bar,\[ScriptB]Bar[[-1]]+ \[ScriptP] (\[Theta]Val-1)];
AppendTo[\[ScriptC],\[ScriptP] + (\[ScriptR]/\[ScriptCapitalR])\[ScriptX][[-1]]];
AppendTo[\[ScriptC]Rat,\[ScriptP]+(\[ScriptR]/\[ScriptCapitalR])\[ScriptX]Bar[[-1]]];
AppendTo[\[ScriptC]Bar,\[Lambda] \[ScriptC]Rat[[-1]]+(1-\[Lambda])\[ScriptC]Bar[[-1]]];
AppendTo[\[ScriptM],\[ScriptX][[-1]]+\[ScriptP]];
AppendTo[\[ScriptM]Bar,\[ScriptX]Bar[[-1]]+\[ScriptP]];
AppendTo[\[ScriptA],\[ScriptM][[-1]]-\[ScriptC][[-1]]];
AppendTo[\[ScriptA]Bar,\[ScriptM]Bar[[-1]]-\[ScriptC]Bar[[-1]]];
\[ScriptC]\[ScriptC]=Take[\[ScriptC],Length[\[ScriptC]]-1];
\[ScriptC]\[ScriptC]Bar=Take[\[ScriptC]Bar,Length[\[ScriptC]Bar]-1];
\[ScriptA]\[ScriptA]=Take[\[ScriptA],Length[\[ScriptA]]-1];
\[ScriptA]\[ScriptA]Bar=Take[\[ScriptA],Length[\[ScriptA]Bar]-1];
];
AddPeriod[2];
Do[AddPeriod[1],{10}];


(* ::Input::Initialization:: *)
Print[cPlot=ListPlot[\[ScriptC],Ticks->{{{1,"t-2"},{2,"t-1"},{3,"t"},{4,"t+1"},{5,"t+2"},{6,"t+3"},{7,"t+4"},{8,"t+5"},{9,"t+6"},{10,"t+7"}},{{1+(0.0001` \[ScriptR])/\[ScriptCapitalR],"1."},{1+\[ScriptR]/\[ScriptCapitalR],"1+r/R"}}},PlotRange->{{0,10.2`},Automatic},AxesLabel->{"Time","\[ScriptCapitalC]"},PlotStyle->PointSize[0.015`]]];



(* ::Input::Initialization:: *)
Print[cBarPlot=ListPlot[\[ScriptC]Bar,Ticks->{{{1,"t-2"},{2,"t-1"},{3,"t"},{4,"t+1"},{5,"t+2"},{6,"t+3"},{7,"t+4"},{8,"t+5"},{9,"t+6"},{10.,"t+7"}},{{1+0.0001 \[ScriptR]/\[ScriptCapitalR],"1."},{1+(\[ScriptR]/\[ScriptCapitalR]),"1+r/R"}}}
,PlotRange->{{0,10.2},Automatic}
,AxesLabel->{"Time","\[ScriptCapitalC]"}
,PlotStyle->{PointSize[0.015],RGBColor[1,0,0]}
]];


(* ::Input::Initialization:: *)
Print[StickyExpectationsCc=Show[cBarPlot,cPlot]];


(* ::Input::Initialization:: *)
Print[xPlot=ListPlot[\[ScriptX],Ticks->{{{1,"t-2"},{2,"t-1"},{3,"t"},{4,"t+1"},{5,"t+2"},{6,"t+3"},{7,"t+4"},{8,"t+5"},{9,"t+6"},{10.,"t+7"}},Automatic}
,PlotRange->{{0,10.2},{-0.02,1.1}}
,AxesOrigin->{0.,0.}
,PlotStyle->{PointSize[0.015],RGBColor[0,0,0]}
,AxesLabel->{"Time","\[ScriptX]"}
]];


(* ::Input::Initialization:: *)
Print[xBarPlot=ListPlot[\[ScriptX]Bar,Ticks->{{{1,"t-2"},{2,"t-1"},{3,"t"},{4,"t+1"},{5,"t+2"},{6,"t+3"},{7,"t+4"},{8,"t+5"},{9,"t+6"},{10.,"t+7"}},Automatic}
,PlotRange->{{0,10.2},{-0.02,1.1}}
,AxesOrigin->{0.,0.}
,AxesLabel->{"Time","\[ScriptX]"}
,PlotStyle->{PointSize[0.015],RGBColor[1,0,0]}
]];


(* ::Input::Initialization:: *)
Print[Show[xPlot,xBarPlot]];


(* ::Input::Initialization:: *)
Print[bPlot=ListPlot[\[ScriptB],Ticks->{{{1,"t-2"},{2,"t-1"},{3,"t"},{4,"t+1"},{5,"t+2"},{6,"t+3"},{7,"t+4"},{8,"t+5"},{9,"t+6"},{10.`,"t+7"}},Automatic}
,PlotRange->{{0,10.2},{-0.02,1.1}}
,AxesOrigin->{0.,0.}
,AxesLabel->{"Time","\[ScriptCapitalB]"},PlotStyle->{PointSize[0.015`],RGBColor[0,0,0]}]];


(* ::Input::Initialization:: *)
Print[bBarPlot=ListPlot[\[ScriptB]Bar,Ticks->{{{1,"t-2"},{2,"t-1"},{3,"t"},{4,"t+1"},{5,"t+2"},{6,"t+3"},{7,"t+4"},{8,"t+5"},{9,"t+6"},{10,"t+7"}},Automatic}
,PlotRange->{{0,10.2},{-0.02,1.1}}
,AxesOrigin->{0.,0.}
,AxesLabel->{"Time","\[ScriptCapitalB]"}
,PlotStyle->{PointSize[0.015],RGBColor[1,0,0]}
]];


(* ::Input::Initialization:: *)
Print[StickyExpectationsCb = Show[bPlot,bBarPlot,BaseStyle->{FontSize->14}]];


(* ::Input::Initialization:: *)
ExportFigsToDir["bPlot","../../Figures"];
ExportFigsToDir["cPlot","../../Figures"];
ExportFigsToDir["StickyExpectationsCb","../../Figures"];
ExportFigsToDir["StickyExpectationsCc","../../Figures"];




