(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



ClearAll["Global`*"];SetDirectory[NotebookDirectory[]];


u[\[ScriptC]_] := (\[ScriptC]^(1-\[Rho]))/(1-\[Rho]);
vFunc[m1_,\[ScriptC]1_] := u[\[ScriptC]1] + u[m1-\[ScriptC]1];


\[Rho] = 2;
{\[ScriptM]Min,\[ScriptM]Mid,\[ScriptM]Max}={4,5,6};
{\[ScriptC]Min,\[ScriptC]Mid,\[ScriptC]Max}={\[ScriptM]Min,\[ScriptM]Mid,\[ScriptM]Max}/2;


Envelope=Show[
Table[
Show[
Plot[v[\[ScriptM]1,\[ScriptC]1],{\[ScriptC]1,\[ScriptM]1/2-.5,\[ScriptM]1/2+.5}
,DisplayFunction->Identity
,PlotRange->{{\[ScriptC]Min-0.5,\[ScriptC]Max+0.5},{vFunc[\[ScriptM]Min,\[ScriptC]Min-0.5],vFunc[\[ScriptM]Max,\[ScriptC]Max]+0.01}}
],
Graphics[{PointSize[Medium],Point[{\[ScriptM]1/2,vFunc[\[ScriptM]1,\[ScriptM]1/2]}]}]
],{\[ScriptM]1,\[ScriptM]Min,\[ScriptM]Max,.2}]
,DisplayFunction->$DisplayFunction
,AxesLabel->{"\!\(\*
StyleBox[\"\[ScriptC]\",\nFontSize->16]\)","\!\(\*
StyleBox[\"v\",\nFontSize->16,\nFontVariations->{\"Underline\"->True}]\)\!\(\*
StyleBox[\"(\",\nFontSize->16]\)\!\(\*
StyleBox[\"\[ScriptM]\",\nFontSize->16]\)\!\(\*
StyleBox[\",\",\nFontSize->16]\)\!\(\*
StyleBox[\"\[ScriptC]\",\nFontSize->16]\)\!\(\*
StyleBox[\")\",\nFontSize->16]\)"}
,ImageSize->{72. 6., 72. 6./GoldenRatio}
,Ticks->None
]


Export["../../Figures/Envelope.pdf",Envelope];
Export["../../Figures/Envelope.png",Envelope,ImageSize->{72. 8.5  ,72. 8.5/GoldenRatio}];(*FullPageSize*)
Export["../../Figures/Envelope.svg",Envelope];
