(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



ClearAll["Global`*"];SetDirectory[NotebookDirectory[]];


Get["./DefinitionsAndAssumptions.m"];ClearVars;
ShowVariableDefinitions;


(* Approximation in the handout *)
\[Kappa]Approx= \[GothicR] - \[Rho]^-1 (\[GothicR]-\[CurlyTheta])-(\[Rho]-1)(\[Stigma]^2 \[Sigma]^2/2);


(* Rewrite the expression and verify that the rewritten version is equivalent *)
{\[Kappa]Approx - (\[GothicR] - \[Rho]^-1 (\[GothicR]-\[CurlyTheta])-(\[Rho]-1)(\[Stigma]^2 \[Sigma]^2/2))
,Simplify[\[Kappa]Approx - (\[Rho]^-1 \[CurlyTheta] +(1- \[Rho]^-1)\[GothicR]-(\[Rho]-1)(\[Stigma]^2 \[Sigma]^2/2))]
}


(* Substitute for \[Stigma] the value that Portfolio-CRRA shows is the optimal choice of \[Stigma] *)
 \[Kappa]Approx2 = \[Kappa]Approx /. \[Stigma] -> \[Phi]/(\[Rho] \[Sigma]^2)


(* Verify some algebraic manipulations of the resulting expression leading to a simplified expression used in handout *)


{Simplify[\[Kappa]Approx2 - (\[Rho]^-1 \[CurlyTheta] +(1- \[Rho]^-1)\[GothicR]-(\[Rho]-1)((\[Phi]/(\[Rho] \[Sigma]^2))^2 \[Sigma]^2/2))]
,Simplify[\[Kappa]Approx2 - (\[Rho]^-1 \[CurlyTheta] +(1- \[Rho]^-1)\[GothicR]-(\[Rho]-1)((\[Phi]/(\[Rho] ))^2 /(\[Sigma]^2 2)))]
,Simplify[\[Kappa]Approx2 - (\[Rho]^-1 \[CurlyTheta] +(1- \[Rho]^-1)\[GothicR]-(1-\[Rho]^-1)((\[Phi]^2/\[Rho] ) /(\[Sigma]^2 2)))]
,Simplify[\[Kappa]Approx2 - (\[Rho]^-1 \[CurlyTheta] +(1- \[Rho]^-1)(\[GothicR]-(\[Phi]^2/\[Rho])/(\[Sigma]^2 2)))]
,Simplify[\[Kappa]Approx2 - (\[Rho]^-1 \[CurlyTheta] +(1- \[Rho]^-1)(\[GothicR]-(\[Phi]^2/(\[Rho] \[Sigma]^2 2))))]
}


\[Kappa]Approx3 = (\[Rho]^-1 \[CurlyTheta] +(1- \[Rho]^-1)(\[GothicR]-(\[Phi]^2/(\[Rho] \[Sigma]^2 2))))


\[Kappa]Approx4=(\[Kappa]Approx3 /.  \[GothicR] ->\[Stigma] \[Phi] + rfree) /. \[Stigma] -> \[Phi]/(\[Rho] \[Sigma]^2)


{
Simplify[\[Kappa]Approx4 - (\[Rho]^-1 \[CurlyTheta] +(1- \[Rho]^-1)(rfree+(\[Phi]^2/(\[Rho] \[Sigma]^2 2))))]
,Simplify[\[Kappa]Approx4 - (\[Rho]^-1 \[CurlyTheta] +(1- \[Rho]^-1)rfree+(1- \[Rho]^-1)((\[Phi]^2/(\[Rho] \[Sigma]^2 2))))]
,Simplify[\[Kappa]Approx4 - (rfree-\[Rho]^-1 (rfree-\[CurlyTheta]) +(1- \[Rho]^-1)((\[Phi]^2/(\[Rho] \[Sigma]^2 2))))]
,Simplify[\[Kappa]Approx4 - (rfree-\[Rho]^-1 (rfree-\[CurlyTheta]) +(\[Rho]- 1)((\[Phi]^2/(\[Rho]^2 \[Sigma]^2 2))))]
}



\[Lambda]=\[GothicR] - (\[GothicR]-\[Rho]^-1 (\[GothicR]-\[CurlyTheta])-(\[Rho]-1)(\[Stigma]^2 \[Sigma]^2/2))


\[Lambda]Sub=Simplify[((\[Lambda] /. \[GothicR] -> rfree+\[Stigma] \[Phi]) /. \[Stigma]->(\[Phi]/(\[Rho] \[Sigma]^2)))]


{Simplify[\[Lambda]Sub - (\[Rho]^-1 (rfree-\[CurlyTheta]))]}


FrontEndExecute[FrontEndToken["DeleteGeneratedCells"]]
